[project]
name = 'delivery-tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.delivery-tracking]
path = 'contracts/delivery-tracking.clar'
clarity_version = 1

[contracts.delivery-tracking-trait]
path = 'contracts/delivery-tracking-trait.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
