[project]
name = 'legal-agreement'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.legal-agreement]
path = 'contracts/legal-agreement.clar'
clarity_version = 1

[contracts.legal-agreement-trait]
path = 'contracts/legal-agreement-trait.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
